version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PB_URL=http://pb:8080
    depends_on:
      - pb

  pb:
    build:
      context: ./backend/pocketbase
    ports:
      - "8080:8080"
    volumes:
      - pb_data:/pocketbase/pb_data

volumes:
  pb_data: